window.bryntum = window.bryntum || {};
window.bryntum.classRename = {
  'GridCellEdit': 'CellEdit',
  'GridGroupSummary': 'GroupSummary',
  'GridSummary': 'GridSummary',
  'GridTreeGroup': 'TreeGroup',
  'GridExcelExporter': 'ExcelExporter',
  'GridPdfExport': 'PdfExport',
  'GridMultiPageExporter': 'MultiPageExporter',
  'GridMultiPageVerticalExporter': 'MultiPageVerticalExporter',
  'GridSinglePageExporter': 'SinglePageExporter',
  'SchedulerTimeAxisColumn': 'TimeAxisColumn',
  'SchedulerAssignmentStore': 'AssignmentStore',
  'SchedulerDependencyStore': 'DependencyStore',
  'SchedulerEventStore': 'EventStore',
  'SchedulerResourceStore': 'ResourceStore',
  'SchedulerPartOfProject': 'PartOfProject',
  'SchedulerProjectCrudManager': 'ProjectCrudManager',
  'SchedulerDependencies': 'Dependencies',
  'SchedulerDependencyEdit': 'DependencyEdit',
  'SchedulerEventResize': 'EventResize',
  'SchedulerLabels': 'Labels',
  'SchedulerSummary': 'Summary',
  'SchedulerPdfExport': 'PdfExport',
  'SchedulerMultiPageExporter': 'MultiPageExporter',
  'SchedulerMultiPageVerticalExporter': 'MultiPageVerticalExporter',
  'SchedulerSinglePageExporter': 'SinglePageExporter',
  'SchedulerAssignmentModel': 'AssignmentModel',
  'SchedulerDependencyModel': 'SchedulerDependencyModel',
  'SchedulerEventModel': 'EventModel',
  'SchedulerProjectModel': 'ProjectModel',
  'SchedulerResourceModel': 'ResourceModel',
  'SchedulerProAssignmentStore': 'AssignmentStore',
  'SchedulerProCalendarManagerStore': 'CalendarManagerStore',
  'SchedulerProDependencyStore': 'DependencyStore',
  'SchedulerProResourceStore': 'ResourceStore',
  'SchedulerProTaskEdit': 'TaskEdit',
  'SchedulerProAssignmentModel': 'AssignmentModel',
  'SchedulerProCalendarIntervalModel': 'CalendarIntervalModel',
  'SchedulerProCalendarModel': 'CalendarModel',
  'SchedulerProDependencyModel': 'DependencyModel',
  'SchedulerProProjectModel': 'ProjectModel',
  'SchedulerProResourceModel': 'ResourceModel'
}
;